---
title: "CDC Public Health Challenge"
author: "Ashira Mawji, Alison Ortiz Damas, Clara Seo"
date: "11/10/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
# Load packages
library(mosaic)  
library(tidyverse)
library(usmap)
library(ggplot2)
library(readxl)

knitr::opts_chunk$set(echo = TRUE)
require(knitr) # knitr settings to control how R chunks work.
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r}
# Import Opioid Data
opioidsCDC <- read_excel("Opioid FINAL Data Set - CDC Challenge (import to R).xlsx")
str(opioidsCDC)
hospital <- read_excel("CDC data 2.xlsx")
```

## Map of United States

```{r}
opioidsCDC <- dplyr::rename(opioidsCDC, state=State)

opioidsCDC <- opioidsCDC %>% 
  mutate(sqrtDeathRate=sqrt(DeathRate)) %>% 
  mutate(VeteranPercent=(VeteranPopu/StatePopu)*100)

plot_usmap(data = opioidsCDC, values = "sqrtDeathRate", lines = "black") + 
  scale_fill_continuous(name = "Sqrt of OD Death Rates \nper 100,000 (2016)", label = scales::comma, high = "#3182bd", low = "#deebf7") + 
  theme(legend.position = "right")

plot_usmap(data = opioidsCDC, values = "VeteranPercent", lines = "black") + 
  scale_fill_continuous(name = "Percentage of Veterans \nby State (2016)", label = scales::comma, high = "#3182bd", low = "#deebf7") + 
  theme(legend.position = "right")

plot_usmap(data = opioidsCDC, values = "VeteranPercent", lines = "black") + 
  scale_fill_continuous(name = "Percentage of Veterans \nby State (2016)", label = scales::comma, high = "#3182bd", low = "#deebf7") + 
  theme(legend.position = "right")
```

## Linear Plot

You can also embed plots, for example:

```{r pressure, echo=FALSE}
ggplot(opioidsCDC, aes(x=DeathRate, y=DemParty/(DemParty+RepParty), col=factor(Region))) +
  xlab("Overdose Death Rates per 100,000") +
  ylab("Proportion of Democratic Representatives") + 
  geom_point() +
  scale_color_discrete(name="Democratic Rep Ratio \nby Region", 
                      breaks=c(1, 2, 3, 4), 
                      labels=c("Northeast", "Midwest", "South", "West"))

ggplot(opioidsCDC, aes(x=DeathRate, y=RepParty/(DemParty+RepParty), col=factor(Region))) +
  ggtitle("") +
  xlab("Overdose Death Rates per 100,000") +
  ylab("Proportion of Republican Representatives") + 
  geom_point() +
  scale_color_discrete(name="Republican Rep Ratio \nby Region", 
                      breaks=c(1, 2, 3, 4), 
                      labels=c("Northeast", "Midwest", "South", "West"))

ggplot(opioidsCDC, aes(x=HighElevation, y=DeathRate)) +
  ggtitle("") +
  ylab("Overdose Death Rates per 100,000") +
  xlab("Highest Elevation by State (feet)") + 
  geom_point()

ggplot(opioidsCDC, aes(x=MeanElevation, y=DeathRate)) +
  ggtitle("") +
  ylab("Overdose Death Rates per 100,000") +
  xlab("Mean Elevation by State (feet)") + 
  geom_point()

ggplot(opioidsCDC, aes(x=MinWage, y=DeathRate)) +
  ggtitle("") +
  ylab("Overdose Death Rates per 100,000") +
  xlab("Minimum Wage by State ($)") + 
  geom_point()

ggplot(opioidsCDC, aes(x=VeteranDisability, y=DeathRate)) +
  ylab("Overdose Death Rates per 100,000") +
  xlab("Disability Rate of Veterans by State") + 
  geom_point()

opioids2 <- mutate(opioidsCDC,VetsPercent=(VetsNo/StatePopu)*100)
opioids2 <- select(opioidsCDC, -c(state,StateAbr,FentanylRate))
pairs(opioids2[c("DeathRate", "HighElevation", "MeanElevation", "MinWage", "VetsNo")])

pairs(opioids2[c("DeathRate", "DemParty/(DemParty+RepParty)", "RepParty/(DemParty+RepParty)", "MinWage", "VetsNo")])
```


